### ISSUE TITLE
Snapshot list regexp brings back all "gcs" snapshots.

### ISSUE THREAD

**Issue by JoeAlamo** [jacksegal/google-compute-snapshot#10]
The following regexp is too inclusive:
````
SNAPSHOT_LIST="$(gcloud compute snapshots list --regexp "(.*gcs-.*)|(.*-${DEVICE_ID}-.*)" --uri)"
````
It matches any snapshot with "gcs" - it's my understanding you only want to match ones for that particular instance based on it's unique ID (see issue #3). Whereas this is matching either (.*gcs-.*) or (.*-${DEVICE_ID}-.*).

Demonstration:
https://regex101.com/r/K2Hcmn/1

If the regex is changed to (gcs-.*${DEVICE_ID}-.*)" --uri) then it only matches snapshots which are in the format gcs-{whatever}-DEVICE_ID-{whatever}.

Demonstration:
https://regex101.com/r/h3N7rs/1

I haven't done a pull request yet on GitHub but I'll make the change and give it a shot.

**Comment by jacksegal** [comment]
Fixed in 9437ee77fbdf990f85d69f18e3be4725246fd641
