### ISSUE TITLE
Deleting more than 1 snapshot fails

### ISSUE THREAD

**Issue by JoeAlamo** [jacksegal/google-compute-snapshot#12]
It seems that when running the actual snapshots delete command, it requires you to confirm the deletion by typing "y" and pressing enter.

This means that when running the snapshot script with a lot of old snapshots, this output occurs:

[Snapshot script output](https://i.imgur.com/S9aTnVx.png)

This line is used to delete the snapshot

````echo "$(gcloud compute snapshots delete ${SNAPSHOT_NAME})"````

We can manually provide a "yes" input to the prompt by changing the line to:

````printf 'y\n' | gcloud compute snapshots delete ${SNAPSHOT_NAME} ````

The output when running with a lot of old/expired snapshots now is:

[Updated snapshot script output](https://i.imgur.com/zVj5CX5.png)

Will make a PR :)

Thank you for the script btw, been really helpful :)

**Comment by jacksegal** [comment]
Fixed in 88acc2d311205a2256f0a53c20cb2fc0e74760a9
