### ISSUE TITLE
v2 - Major Changes

### ISSUE THREAD

**Issue by jacksegal** [jacksegal/google-compute-snapshot#15]
@dborin, @JoeAlamo - Thanks for your contributions to the project!

I've made some Major Changes to the code and done a new release under tag [2.0.1](https://github.com/jacksegal/google-compute-snapshot/releases/tag/2.0.1).

The code is now function based, for easier testing (coming soon...) and modifications.  I've also re-done the README to include "beefier" installation instructions.

If you want to stick with the old version, I tagged it under [1.0.0](https://github.com/jacksegal/google-compute-snapshot/releases/tag/1.0.0) and [1.0.1](https://github.com/jacksegal/google-compute-snapshot/releases/tag/1.0.1) with @dborin's PR that he raised today.

If you guys would like to use the latest version, I'd love to hear how you get on (any bugs, issues with instructions, etc.).  I've tested it on my preferred distro (Debian 8) and it works fine.

From a coding point of view, the project is made up of lots of small light-weight functions, which are grouped together by 2 wrapper functions: createSnapshotWrapper & deleteSnapshotsWrapper.

Like I said, I'm hoping to add in some test cases over the next week or two.

**Comment by dborin** [comment]
you aren't calling out that the cronjob has to be able to run as the GCE
user that is authorized

**Comment by dborin** [comment]
This doesn't work at all for non-Debian Linux versions, specifically CentOS
6 (yeah, don't ask).

While I appreciate the effort, I like the simple script as it works now
(v1) and will prolly keep my fork there.  You can look at the change I had
to make to get it to work for an older distro and incorporate it in to v2
if you would like.

https://github.com/dborin/google-compute-snapshot/commit/da982a1e6043ec8b47f789530181b328495b564f

**Comment by jacksegal** [comment]
Cheers for taking a look @dborin - I may write some tests to see exactly which bits don't work for non-Debian versions.

**Comment by pastorjustin** [comment]
Hey, so would you be willing to show me how to make this work in Windows?  The google cloud SDK is present and it works well.  I can type gcloud compute disks snapshot INSTANCENAME --snapshot-names=SNAPSHOTNAME --zone=ZONENAME and the backups get created, but I need a little direction on how to make the script you wrote work in windows.  I am thinking we may need to re-do it in powershell...

**Comment by jacksegal** [comment]
Hi @pastorjustin - I've never used powershell before, so I don't know how easy that would be.  If I get some spare time over the next week, I'll try downloading it and seeing how easy it is to rewrite commands like "curl"

**Comment by koenvdvelde** [comment]
Hi Jack,
I'm trying to run your snapshot script on our bitnami/redmine installation.
It does however generate this error : 
>>ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
>>  - The resource 'projects/wise-scene-118518/zones/europe-west1-c/disks/redmine-vm-tmpl-boot-disk' was not found

I already checked devicename and zone  : 
# curl -s "http://metadata.google.internal/computeMetadata/v1/instance/disks/0/device-name" -H "Metadata-Flavor: Google" -w "\n"
redmine-vm-tmpl-boot-disk
# curl -s "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google" -w "\n"
projects/532378551261/zones/europe-west1-c

It 's the device-name I'm worried about:   When checking my project disks trough the google cloud console, there is only one disk and it's named "redmine-1-vm" ... not "redmine-vm-tmpl-boot-disk".

Thanks in advance for your assistance,
Koen.

**Comment by jacksegal** [comment]
Hi Koen,

It could be that you've deleted a disk - can you run the following 2
commands and let me know the output:

$ gcloud compute disks list

$ curl -s "
http://metadata.google.internal/computeMetadata/v1/instance/disks/1/device-name"
-H "Metadata-Flavor: Google" -w "\n"

Thanks,

Jack


On Wed, 28 Dec 2016, 14:19 koenvdvelde, <notifications@github.com> wrote:

Hi Jack,
I'm trying to run your snapshot script on our bitnami/redmine installation.
It does however generate this error :

ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:

   - The resource
   'projects/wise-scene-118518/zones/europe-west1-c/disks/redmine-vm-tmpl-boot-disk'
   was not found

I already checked devicename and zone :
curl -s "
http://metadata.google.internal/computeMetadata/v1/instance/disks/0/device-name"
-H "Metadata-Flavor: Google" -w "\n"

redmine-vm-tmpl-boot-disk
curl -s "http://metadata.google.internal/computeMetadata/v1/instance/zone"
-H "Metadata-Flavor: Google" -w "\n"

projects/532378551261/zones/europe-west1-c

It 's the device-name I'm worried about: When checking my project disks
trough the google cloud console, there is only one disk and it's named
"redmine-1-vm" ... not "redmine-vm-tmpl-boot-disk".

Thanks in advance for your assistance,
Koen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacksegal/google-compute-snapshot/issues/15#issuecomment-269483019>,
or mute the thread

**Comment by koenvdvelde** [comment]
Hello Jack,
thanks for your quick response.

this the output of the commands : 
>gcloud compute disks list
>>NAME          ZONE            SIZE_GB  TYPE         STATUS
>>redmine-1-vm  europe-west1-c  10       pd-standard  READY

>curl -s " http://metadata.google.internal/computeMetadata/v1/instance/disks/1/device-name" -H "Metadata-Flavor: Google" -w "\n"
>> NO OUTPUT

K.

**Comment by jacksegal** [comment]
Okay, can you try this one too:

$ curl "http://metadata.google.internal/computeMetadata/v1/instance/disks/"
-H "Metadata-Flavor: Google"

**Comment by koenvdvelde** [comment]
here it is ...
> curl "http://metadata.google.internal/computeMetadata/v1/instance/disks/" -H "Metadata-Flavor: Google"
>>0/

**Comment by jacksegal** [comment]
Okay, lets just check that all the permissions are working correctly - can
you run the following command:

$ gcloud compute disks snapshot redmine-1-vm --snapshot-names
manual_test_1483005972 --zone europe-west1-c

Can you also run the following gcloud command - no idea why gcloud is
returning a different device name to gcloud, but it might be possible to
switch:

$ gcloud compute disks list --uri

**Comment by koenvdvelde** [comment]
Hi Jack,
to create the snapshot, I had to remove the "_" from the name, but other than that, it worked fine : 

$ gcloud compute disks snapshot redmine-1-vm --snapshot-names manualtest1483005972 --zone europe-west1-c
Created [https://www.googleapis.com/compute/v1/projects/wise-scene-118518/global/snapshots/manualtest1483005972].

$ gcloud compute disks list --uri
https://www.googleapis.com/compute/v1/projects/wise-scene-118518/zones/europe-west1-c/disks/redmine-1-vm

$ gcloud compute snapshots list
NAME                   DISK_SIZE_GB  SRC_DISK                           STATUS
manualtest1483005972   10            europe-west1-c/disks/redmine-1-vm  READY
redmine-1-vm-20160606  10            europe-west1-c/disks/redmine-1-vm  READY
redmine-1-vm-20161115  10            europe-west1-c/disks/redmine-1-vm  READY
redmine-1-vm-20161121  10            europe-west1-c/disks/redmine-1-vm  READY
redmine-1-vm-20161221  10            europe-west1-c/disks/redmine-1-vm  READY
redmine-basis          10            europe-west1-c/disks/redmine-1-vm  READY

**Comment by jacksegal** [comment]
Okay, I have no idea why the gcloud command is returning a different value
to the MetaData, but I've created a new branch "device-name-from-cloud"
which uses gcloud to get the device-name in the function "getDeviceName".

You can download the new branch, using the following commands:

$ cd ~
$ wget
https://raw.githubusercontent.com/jacksegal/google-compute-snapshot/4acc3ef0acb2b5d784d15af79f25642c744938e2/gcloud-snapshot.sh
$ chmod +x gcloud-snapshot.sh
$ sudo mkdir -p /opt/google-compute-snapshot
$ sudo mv gcloud-snapshot.sh /opt/google-compute-snapshot/

You can test it with:

$ sudo /opt/google-compute-snapshot/gcloud-snapshot.sh

Let me know if that works - if it does, I'll merge it into master.

**Comment by koenvdvelde** [comment]
Works like a glance !!
root@redmine-1-vm:/opt/google-compute-snapshot# ./gcloud-snapshot.sh
2016-12-29 11:36:34: Start of Script
2016-12-29 11:36:34: Start of createSnapshotWrapper
Created [https://www.googleapis.com/compute/v1/projects/wise-scene-118518/global/snapshots/gcs-redmine-1-vm-5808340041993364782-1483011394].
2016-12-29 11:36:57: Start of deleteSnapshotsWrapper
2016-12-29 11:36:59: End of Script
root@redmine-1-vm:/opt/google-compute-snapshot# gcloud compute snapshots list
NAME                                             DISK_SIZE_GB  SRC_DISK                           STATUS
gcs-redmine-1-vm-5808340041993364782-1483011394  10            europe-west1-c/disks/redmine-1-vm  READY
manualtest1483005972                             10            europe-west1-c/disks/redmine-1-vm  READY

Thanks a lot !
Koen.

**Comment by jacksegal** [comment]
Great, glad to hear it.  If you like the repo, don't forget to star it! :-)

I've merged it into master, so you can do the normal installation
instructions:

cd ~
wget https://raw.githubusercontent.com/jacksegal/google-compute-snapshot/master/gcloud-snapshot.sh
chmod +x gcloud-snapshot.sh
sudo mkdir -p /opt/google-compute-snapshot
sudo mv gcloud-snapshot.sh /opt/google-compute-snapshot/
