### ISSUE TITLE
option -d ignored & snapshot delete gives error

### ISSUE THREAD

**Issue by koenvdvelde** [jacksegal/google-compute-snapshot#18]
Hi Jack,
I had to make some changes to your code in order to make the snapshot delete work : 

1) -d option was ignored because the command line arguments were not processed by the setScriptOptions() function. 

FIX : 
```
310c310
< setScriptOptions
---
> setScriptOptions "$@"
```

2) error when deleting snapshot : 
>ERROR: (gcloud.compute.snapshots.delete) too few arguments
>Usage: gcloud compute snapshots delete  NAME [NAME ...] [optional flags]

FIX : 
```
291c291
<            OUTPUT_SNAPSHOT_DELETION=$(deleteSnapshot) ${snapshot}
---
>            OUTPUT_SNAPSHOT_DELETION=$(deleteSnapshot ${snapshot})
```
Kind regards,
Koen.

**Comment by koenvdvelde** [comment]
please ignore remark (2) ... it's a bugfix for a bug I seem to have introduced myself ... sorry.

sorry,
Koen.

**Comment by jacksegal** [comment]
Cheers Koen - I've updated master!
