### ISSUE TITLE
insuffusient permissions?

### ISSUE THREAD

**Issue by aelsharawi** [jacksegal/google-compute-snapshot#2]
I CHMOD the file to 0755 and when i run it from ssh

i got 

```
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Insufficient Permission

ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission
usage: gcloud compute snapshots describe  NAME [optional flags]
ERROR: (gcloud.compute.snapshots.describe) too few arguments
date: invalid date ‘+%Y%m%d’
./1.sh: line 48: [: 20160509: unary operator expected
root@wordpress-ngx-php7:~/autosnapshots# chmod 7777 1.sh
root@wordpress-ngx-php7:~/autosnapshots# ./1.sh
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Insufficient Permission

ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission
usage: gcloud compute snapshots describe  NAME [optional flags]
ERROR: (gcloud.compute.snapshots.describe) too few arguments
date: invalid date ‘+%Y%m%d’
```

**Comment by jacksegal** [comment]
Hey,

Can you run the following commands manually and let me know the output?

`curl -s "http://metadata.google.internal/computeMetadata/v1/instance/disks/0/device-name" -H "Metadata-Flavor: Google"  -w "\n"`

`curl -s "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google"  -w "\n"`

`date "+%Y%m%d%H%M%S"`

**Comment by aelsharawi** [comment]
1 `wordpress-ngx-php7`

2 `projects/2529778301/zones/europe-west1-d`


3-` 20160516134009`

**Comment by jacksegal** [comment]
I think it is because maybe you haven't done the [gcloud auth login](https://cloud.google.com/sdk/gcloud/reference/auth/login).

Can you run the following command and see if that fixes the problem?  If so, I'll add it as a prerequisite.

```gcloud auth login```

**Comment by aelsharawi** [comment]
```
root@wordpress-ngx-php7:~/autosnapshots# ./1.sh
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Insufficient Permission

ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission
usage: gcloud compute snapshots describe  NAME [optional flags]
ERROR: (gcloud.compute.snapshots.describe) too few arguments
date: invalid date ‘+%Y%m%d’
./1.sh: line 48: [: 20160510: unary operator expected
root@wordpress-ngx-php7:~/autosnapshots# sudo ./1.sh
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Insufficient Permission

ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission
usage: gcloud compute snapshots describe  NAME [optional flags]
ERROR: (gcloud.compute.snapshots.describe) too few arguments
date: invalid date ‘+%Y%m%d’
./1.sh: line 48: [: 20160510: unary operator expected
```


I re-authenticated howver the same problem

**Comment by aelsharawi** [comment]
my system is jessy by the way

**Comment by jacksegal** [comment]
It seems the issue is with your Google permissions and not the code.

Can you try running the following command manually:
```gcloud compute disks snapshot wordpress-ngx-php7 --snapshot-names wordpress-ngx-php7-20160516134009 --zone europe-west1-d```

From a quick googling about gcloud permissions (I'm not a pro), it seems that the permission issue can be caused be a few possible things:

- No billing setup (have you got billing setup properly?)
- The google account used for authenticating not having the correct project rights (are you admin?)

There are a few [forums](https://groups.google.com/forum/#!topic/gce-discussion/f0PW-bGEWvk) that mention you need to give the VM "project access" whilst you're setting it up, although it also says you can resolve that afterwards (if you didn't give it access) by doing the `gcloud auth login` command.

**Comment by aelsharawi** [comment]
the command u just sent worked just fine to create the snapshot.

-Im the admin and I have the billing just fine

**Comment by aelsharawi** [comment]
here is my api settings


Cloud API access scopes

BigQuery	
Disabled
Bigtable Admin	
Disabled
Bigtable Data	
Disabled
Cloud Datastore	
Disabled
Cloud Logging API	
Write Only
Cloud Monitoring API	
Write Only
Cloud Pub/Sub	
Disabled
Cloud SQL	
Disabled
Cloud User Accounts	
Read Only
Compute	
Disabled
Service Control	
Disabled
Service Management	
Disabled
Storage	
Read Only
Task queue	
Disabled
User info	
Disabled

**Comment by jacksegal** [comment]
Okay, if the gcloud command works by itself, then that suggests it could an issue with how the shell file is being executed.

What command are you using?  Is it ```sh /1/snapshot.sh``` ?  (providing that the file is in the directory `/1` and the filename is `snapshot.sh`)

**Comment by aelsharawi** [comment]
thanks for bearing with me with that my commands are

` git clone https://github.com/jacksegal/google-compute-snapshot`

`cd google-compute-snapshot`

`chmod 0750 snapshot.sh`

`./snapshot.sh`

**Comment by jacksegal** [comment]
my pleasure - i'm sure we can get to the bottom of it soon!

can you try adding `sh` before the command?  so `sh snapshot.sh`

**Comment by aelsharawi** [comment]
`root@wordpress-ngx-php7:~/google-compute-snapshot# sh snapshot.sh
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Insufficient Permission

ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission
usage: gcloud compute snapshots describe  NAME [optional flags]
ERROR: (gcloud.compute.snapshots.describe) too few arguments
date: invalid date ‘+%Y%m%d’
snapshot.sh: 48: [: -ge: argument expected`

**Comment by aelsharawi** [comment]
same error :)

**Comment by aelsharawi** [comment]
is it related to Debian? 

can u make a virtual machine with Jessie and see?

**Comment by jacksegal** [comment]
No, I don't think it is that - I am using Debian Jessie (8.3).

I've just redone all of the commands you did and it worked for me.

Which user are you cloning the repo as?  Are you executing the sh file as the same user as you did `gcloud auth login` with?

**Comment by aelsharawi** [comment]
yes and with the root user too, both fails

I created a new virtual machine from the scratch and also didnt work

I will try to add the cron and see if that work, maybe the cron will do it

**Comment by jacksegal** [comment]
hmmmm - i've just done the same commands you listed again and it worked - how strange!

sorry, not sure there is anything else i can do for you... maybe have a look at this answer about permissions regarding compute: http://stackoverflow.com/questions/31905966/gcloud-compute-list-networks-error-some-requests-did-not-succeed-insufficie#31928399

i'm not a google cloud permission wizard, so can't say for sure if that is your problem or not.  seems very strange that you could run all of the commands manually though.  maybe try deleting the first 2 lines of the code?  don't see why that would fix it, but might be worth having a go...

sorry, all out of ideas!

**Comment by aelsharawi** [comment]
wonderfull, THE PROBLEM WAS ON: api access ,the above article solved the issue

-the problem now is the script deleted the old snapshots that was not created by the script it self, which is not nice at all, hope there is a fix to that.

**Comment by jacksegal** [comment]
I've done it in commit: `6944bb5e2137942f683371e4869e8513ee487080`

The script now only deletes snapshots that:

1. Are for the VM that the script is running on
2. That were created by the script

This means that it won't delete the existing snapshots created in the last 7 days (when they become "expired"), because the existing snapshots do not meet the new criteria.

I suggest manually deleting them in 10 days time.

**Comment by aelsharawi** [comment]
```
ERROR: (gcloud.compute.disks.snapshot) Some requests did not succeed:
 - Invalid value for field 'snapshot.name': 'gcs-auto-bkup-nginx-redis-php7-cloudsql-6251049912065750217-20160602031350'. Must be a match of regex '(?:[a-z](?:[-a-z
0-9]{0,61}[a-z0-9])?)'
usage: gcloud compute snapshots describe  NAME [optional flags]
ERROR: (gcloud.compute.snapshots.describe) too few arguments
date: invalid date ‘+%Y%m%d’
1/snapshot.sh: 50: [: -ge: argument expected
```

am I doing something wrong?

**Comment by jacksegal** [comment]
Hi,

No, you're not doing anything wrong - now that I've added the device id to
the name, it has exceeded the character limit for your device.

I will push a proper fix for it this week, but if you need to fix it in the
meantime then change line 34 to:

echo "$(gcloud compute disks snapshot ${DEVICE_NAME} --snapshot-names
gcs-auto-bkup-${DEVICE_ID}-${DATE_TIME} --zone ${INSTANCE_ZONE})"

This will put the snapshot name under the character limit.

Thanks,
Jack

**Comment by jacksegal** [comment]
Hi,

I've released a fix to the code - commit:
6bdd604a4730c73b34de1c8e251882cc0e632e78

Thanks,
Jack

**Comment by aelsharawi** [comment]
I have tried it under centos 6

`Created [https://www.googleapis.com/compute/v1/projects/grand-hi3334/global/snapshots/gcs-wp-8101706970078175269-1468260147].
date: invalid date `2016-07-11T10:59:58.850-07:00'
snapshot.sh: line 50: [: 20160704: unary operator expected
date: invalid date `2016-07-11T11:00:38.671-07:00'
snapshot.sh: line 50: [: 20160704: unary operator expected
date: invalid date `2016-07-11T11:02:28.490-07:00'
snapshot.sh: line 50: [: 20160704: unary operator expected`


what do u think?

**Comment by hallard** [comment]
@jacksegal 
Very nice script, thanks for sharing. 
Anyway I forgot the magic line 

```
gcloud auth login
```

Worth mentioning that mandatory step in the README.md ;-)
