### ISSUE TITLE
Cron command doesn't work

### ISSUE THREAD

**Issue by MrBrotato** [jacksegal/google-compute-snapshot#22]
I'm a newbie so I could be doing something wrong or maybe I shouldn't even be submitting this but the README guide provides an example cron command which doesn't work:

`0 5 * * * root /opt/google-compute-snapshot/gcloud-snapshot.sh >> /var/log/cron/snapshot.log 2>&1`

Again, as a newbie I'm not even sure I belong here. I Googled a while and tried `-u root` but that also produced an error in the log.

**Comment by xyzulu** [comment]
You'll need to use the exact command that works via SSH. Personally I created a .sh bash script and I call it using: sh /path/to/script.sh 

Make sure you have the correct shebang in your file and that permissions are set correctly if you use my method.

**Comment by jacksegal** [comment]
No worries - we were all newbies once!

Does it work when you just run the command by itself?
(/opt/google-compute-snapshot/gcloud-snapshot.sh)

Also, how are you doing the CRON? Is it via crontab? If so, you'll need to
remove the "root".

I do my crons via /etc/cron.d so i have to specify which user the command
should be run by.

**Comment by MrBrotato** [comment]
Thank you both. I did get it working.

I had never setup a cron job before without doing it through some kind of web interface or something so when I googled how to do it I found the `crontab -e` method and just copied the command into that which of course didn't work. It is working great now that I removed the `root` and `-u root` variations I had tried.

**Comment by jacksegal** [comment]
Great, glad it's working for you!
