### ISSUE TITLE
sudo mkdir /var/log/cron not adirectory

### ISSUE THREAD

**Issue by aelsharawi** [jacksegal/google-compute-snapshot#23]
Hello

Im on centos 7 and this command shows that is not dire it is a file, so I cant follow the steps of the log, please help

**Comment by jacksegal** [comment]
I've never tested it with centos 7, so the best thing to do is make sure the actual script works by running the following command:
`sudo /opt/google-compute-snapshot/gcloud-snapshot.sh`

Let me know if that works - if it does, then we can sort out the rest, as the command that is failing for you is only used for setting up cron logs.

**Comment by aelsharawi** [comment]
the command works just fine, the problem is in cron log

**Comment by aelsharawi** [comment]
`0 5 * * * root /opt/google-compute-snapshot/gcloud-snapshot.sh >> /var/log/cron/snapshot.log 2>&1
`

**Comment by aelsharawi** [comment]
CentOS doesn't have a directory called /var/log/cron only a file called /var/log/cron by default

I created another file and will see what can be done

**Comment by aelsharawi** [comment]
and made this
sudo nano /etc/logrotate.d/cron

`/var/log/*.log {
    daily
    missingok
    rotate 14
    compress
    notifempty
    create 664 root adm
    sharedscripts
}
`

**Comment by aelsharawi** [comment]
very strange,

after making these change and just yum update, I failed to get into the server

and was lucky that i have a backup

however the crontab shows one line of @^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@


any help?

**Comment by aelsharawi** [comment]
the server locking was from CSF

however the log now shows"

/bin/sh: root: command not found

**Comment by jacksegal** [comment]
For setting up CRONs on Centos 7, here are some instructions:
https://www.rosehosting.com/blog/automate-system-tasks-using-cron-on-centos-7/

It seems that you should be using crontab (rather than cron.d), so you
don't need to include the "root" part of the CRON command (when using
cron.d you need to specify which user should run the command).  The
following command should be in root's crontab:

0 5 * * * /opt/google-compute-snapshot/gcloud-snapshot.sh >>
/var/log/cron/snapshot.log 2>&1

Does that make sense?  Let me know if you have any problems.

If the /var/log/cron directory is causing issues, then maybe it is best to
just silence the output and not record anything (by using /dev/null):

0 5 * * * /opt/google-compute-snapshot/gcloud-snapshot.sh >/dev/null 2>&1

**Comment by aelsharawi** [comment]
ok, why the snapshot that was made using the command, this snapshot had the crontab scrambled text:

`@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@`

**Comment by jacksegal** [comment]
Sorry, I don't understand the question?

**Comment by aelsharawi** [comment]
stepes to produce that
1-run the snapshot command directly on the ssh
2-a snapshot is created
3-the new snapshot restored to a new VPS
4-trying to edit the crontab from the new restored snapshot
5-I found the whole crontab fulled with this text without any thing else
`@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@`

**Comment by jacksegal** [comment]
Right, thanks for that - understand you.

Does that happen when you run the command manually (not through crontab)?: sudo
/opt/google-compute-snapshot/gcloud-snapshot.sh

Or does that only happen when you run it through crontab? I think the issue
here is with the output - I think it is best to silence it using /dev/null:

0 5 * * * /opt/google-compute-snapshot/gcloud-snapshot.sh >/dev/null 2>&1

**Comment by aelsharawi** [comment]
this happened when run manually, I didn't test more than that,

but, do u think text was scrambled because of that? will there any text that was corrupted beside that?

**Comment by jacksegal** [comment]
I don't think the scrambled text has anything to do with the script - it might have been done when you were trying to setup the CRON & CRON output (/var/log/cron).  I've never used centos though, so can't say for sure.

**Comment by aelsharawi** [comment]
Thanks a lot, I repeated the process again, and it went fine without any errors or scrambled text, maybe it was as u said befoe.

**Comment by jacksegal** [comment]
Great!  Glad it's working for you.

**Comment by aelsharawi** [comment]
here is the google engineer reply:

 This issue could be related to the snapshot not properly created in the past. Recommended methods to create the disk snapshots are documented on this link[1].

As your issue is resolved now, I'll go ahead and close this issue report. In further, if you are still affected please feel free to open a new issue which refers back to this one for context.

[1] https://cloud.google.com/compute/docs/disks/create-snapshots#creating_snapshots

**Comment by jacksegal** [comment]
Hi @aelsharawi - why have you re-opened the issue?

It's working now for you and we think we know the cause (setting up CRON on centos).

We are using the method recommended in the link (gcloud).

**Comment by aelsharawi** [comment]
sorry for that 🥇
