### ISSUE TITLE
GetDeviceName does not works

### ISSUE THREAD

**Issue by shaphiro** [jacksegal/google-compute-snapshot#24]
The getDeviceName function does not returns the device attached to the vm. I suggest to 
` -local vm_name="$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/name" -H "Metadata-Flavor: Google")"
    -local device_name="$(gcloud compute disks list ${vm_name} --uri)"

   +local device_name="$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/disks/0/device-name" -H "Metadata-Flavor: Google")"`

**Comment by jacksegal** [comment]
Thanks for raising and sorry for the late reply - been crazy busy recently.

I was using the metadata call for the device name before, but someone was having an issue where it was returning a disk that had been deleted - think it was a cache issue.

Can you let me know the output if you manually run the commands?  I can then take a further look into it.

1) `$ (curl -s "http://metadata.google.internal/computeMetadata/v1/instance/name" -H "Metadata-Flavor: Google")`
2) using output from above command... `$(gcloud compute disks list ${vm_name} --uri)`
3) `$(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/disks/0/device-name" -H "Metadata-Flavor: Google")`

**Comment by jacksegal** [comment]
Closing this issue - please provide the info you want me to investigate further.

Thanks,
Jack
