### ISSUE TITLE
script uses deprecated filter and regexp flags

### ISSUE THREAD

**Issue by artooro** [jacksegal/google-compute-snapshot#26]
I am seeing 2 warnings.
`WARNING: Argument NAME is deprecated. Use --filter="name=( 'NAME' ... )" instead.`
and
`WARNING: Flag --regexp is deprecated. Use --filter="name~'REGEXP'" instead.`

**Comment by jacksegal** [comment]
Thanks @artooro - I saw them recently.

The commands still work - I am going to change the code to use `---filter` soon.

**Comment by GauravSharma531** [comment]
I am also facing the same issue

**Comment by jacksegal** [comment]
@artooro, @GauravSharma531,

I've created a new branch with a fix for the warnings - are you able to give it a quick test to make sure it works for you?

I've tested it on a few different VM's and it's working fine for me:

```
cd ~
wget https://raw.githubusercontent.com/jacksegal/google-compute-snapshot/master/gcloud-snapshot.sh
chmod +x gcloud-snapshot.sh
sudo mkdir -p /opt/google-compute-snapshot
sudo mv gcloud-snapshot.sh /opt/google-compute-snapshot/filter-gcloud-snapshot.sh
sudo /opt/google-compute-snapshot/filter-gcloud-snapshot.sh
```

Let me know how you get on

**Comment by jacksegal** [comment]
Merged PR into master
