### ISSUE TITLE
Support Multiple Disks per Instance

### ISSUE THREAD

**Issue by jacksegal** [jacksegal/google-compute-snapshot#27]
Currently the script only supports the primary disk on an instance - it ignores any additional ones.

The script should be enhanced so that it takes a backup of **all** disks on an instance.

This functionality has already been added in forked versions:

- [awasilyev](https://github.com/awasilyev/google-compute-snapshot/commit/cdc74467479527132c6af016f34ddab4bf1fe886)
- [jeremywadsack](https://github.com/keylimetoolbox/google-compute-snapshot/commit/2bdee999837b40e1f691b0a1567439ce1d43a75d)

**Comment by randinterval** [comment]
@jacksegal  Thanks Jack, Was looking for multi disk support!

**Comment by jacksegal** [comment]
Latest release contains this functionality! 

https://github.com/jacksegal/google-compute-snapshot/releases/tag/3.0.0

(FYI: @randinterval  / @logTom)

**Comment by randinterval** [comment]
@jacksegal  Yes, using it on a bunch of instances now! Thanks a lot :+1:
