### ISSUE TITLE
Default snapshot deletion is dangerous for compliance. The device_name var will be blank if the current project is not the right one.  Argument NAME is deprecated.

### ISSUE THREAD

**Issue by nestoru** [jacksegal/google-compute-snapshot#30]
Greetings,

Thanks for putting it simple as it should be ;-)

I forked it in https://github.com/nestoru/google-compute-snapshot and corrected the three issues I mention in the subject. If you need a PR please let me know.

Cheers,
- Nestor

**Comment by jacksegal** [comment]
Hi Nestor,

Thanks for your feedback!  Sorry for the late response too...

- I've already fixed the "Argument NAME is deprecated" issue
- I understand why you might think the default deletion date is dangerous, but I am going to leave it in (you can pass the deletion date as a parameter, so could set it to something like 3650 days / 10 years)
- I don't understand why / how the current project could be "the wrong one"?  If you want to provide some examples for this, I'll happily investigate!

Thanks,
Jack
