### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NudeWeb** [jacksegal/google-compute-snapshot#33]
I'm getting the following error when I run sudo /opt/google-compute-snapshot/gcloud-snapshot.sh

ERROR: (gcloud.compute.disks.list) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials, or if you have already logged in with a
different account:

  $ gcloud config set account ACCOUNT

Not sure what I can do to fix this.

**Comment by jacksegal** [comment]
Hi @NudeWeb - it's a problem with gcloud permissions.  Here is a StackOverflow explanation of how to resolve it: https://stackoverflow.com/questions/31905966/gcloud-compute-list-networks-error-some-requests-did-not-succeed-insufficie#31928399
