### ISSUE TITLE
getDeviceList gets disks for other instances with names that include the current instance's name

### ISSUE THREAD

**Issue by rvaidya** [jacksegal/google-compute-snapshot#34]
Example, two instances:
wordpress
wordpress-mysql

echo "$(gcloud compute disks list --filter users~wordpress --format='value(name)')"

will match against both instances.

This needs to be

echo "$(gcloud compute disks list --filter users~$1\\$ --format='value(name)')"

**Comment by jacksegal** [comment]
Thanks for the feedback - will run some tests later today and if all goes well apply the fix

**Comment by jacksegal** [comment]
@rvaidya, thanks again for the feedback - I've pushed your change to master.

**Comment by rvaidya** [comment]
Same issue also is there for names matching at the start, i'm changing my expression to be

`echo "$(gcloud compute disks list --filter \"users~instances/$1\$ AND labels.auto_snapshot=true\" --format='value(name)')"`
