### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by tomusher** [jacksegal/google-compute-snapshot#37]
Thanks for this project, it looks very useful!

It would be great if you could include a license so we can use/modify it (https://choosealicense.com/no-permission/)

**Comment by jacksegal** [comment]
Thanks for the heads up about the license - been meaning to sort one, but it's my first project and just never got round to it - went with MIT as it seemed the easiest.

If you do modify / improve it - do let me know so I can add them to the repo 👍
