### ISSUE TITLE
Unrecognized Arguments 

### ISSUE THREAD

**Issue by kdehollander** [jacksegal/google-compute-snapshot#42]
$ ./gcloud-snapshot.sh 
2018-06-18 17:12:02: Start of Script
2018-06-18 17:12:02: Start of createSnapshotWrapper
usage: gcloud compute disks list  [NAME ...] [optional flags]
ERROR: (gcloud.compute.disks.list) unrecognized arguments: --filter
usage: gcloud compute disks snapshot  DISK_NAME [DISK_NAME ...] [optional flags]
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
2018-06-18 17:12:03: Start of deleteSnapshotsWrapper
usage: gcloud compute snapshots list  [NAME ...] [optional flags]
ERROR: (gcloud.compute.snapshots.list) unrecognized arguments: --filter=name~'gcs-.*2079002971386815162-.*'
2018-06-18 17:12:04: End of Script

Are the GCloud API calls still up to date?

**Comment by jacksegal** [comment]
hi @kdehollander,

yes, they should be - can you check what version of gcloud you're using?  just type the following command on the VM you're trying to execute the script on: `$ gcloud -v`

**Comment by kdehollander** [comment]
I did a quick gcloud component update and oauth login, and it succeeded. 
Thanks for the tip!
