### ISSUE TITLE
Script error Some requests did not succeed for disk.list disk.snapshot and snapshot.list 

### ISSUE THREAD

**Issue by juranich** [jacksegal/google-compute-snapshot#46]
Hi,
When I try to run the script it gives me an error. I presume this is permission issues but can't figure out which ones.

I've activated a service account with Compute Engine Admin and Compute Storage Admin rights.
Here is what I get.
```
$ gcloud compute snapshots list
NAME        DISK_SIZE_GB  SRC_DISK                         STATUS
snapshot-1  10            europe-west1-b/disks/axxoncrm-1  READY
$ gcloud compute disks list
NAME        ZONE            SIZE_GB  TYPE         STATUS
axxoncrm-1  europe-west1-b  10       pd-standard  READY
$ sudo /opt/google-compute-snapshot/gcloud-snapshot.sh
2018-07-26 10:13:13: Start of Script
2018-07-26 10:13:13: Start of createSnapshotWrapper
ERROR: (gcloud.compute.disks.list) Some requests did not succeed:
 - Insufficient Permission
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
Usage: gcloud compute disks snapshot DISK_NAME [DISK_NAME ...] [optional flags]
  optional flags may be  --async | --csek-key-file | --description |
                         --guest-flush | --help | --snapshot-names | --zone
For detailed information on this command and its flags, run:
  gcloud compute disks snapshot --help
2018-07-26 10:13:35: Start of deleteSnapshotsWrapper
ERROR: (gcloud.compute.snapshots.list) Some requests did not succeed:
 - Insufficient Permission
2018-07-26 10:13:55: End of Script
```

**Comment by juranich** [comment]
Hi @jacksegal,

Yes I've read that post. The problem is that my instance is already created and I can't see how I can change Compute to Enable. It does mention it in the post that you can use Service Account, which I have, but didn't go into detail what roles to assign.

**Comment by jacksegal** [comment]
Right, with you - can you try running the following gcloud commands using `sudo`?

```
sudo gcloud compute snapshots list
sudo gcloud compute disks list
```

I can see from your first output that when you run the commands outside of the script it does look like it's working, so maybe that's worth checking. 

If it works using `sudo` (which I expect it will), it might be worth trying the following commands too, to see if it's actually another command failing:

**DATE_TIME**
`date "+%s"`

**INSTANCE_NAME**
`curl -s "http://metadata.google.internal/computeMetadata/v1/instance/hostname" -H "Metadata-Flavor: Google"`

**INSTANCE_ID**
`curl -s "http://metadata.google.internal/computeMetadata/v1/instance/id" -H "Metadata-Flavor: Google"`

**INSTANCE_ZONE**
`curl -s "http://metadata.google.internal/computeMetadata/v1/instance/zone" -H "Metadata-Flavor: Google"`

**DEVICE_LIST** _(replacing "instance_name" whatever value you got from the INSTANCE_NAME command)_
`gcloud compute disks list --filter users~instance_name\$ --format='value(name)'`

**Comment by juranich** [comment]
@jacksegal you were right, when I ran `sudo gcloud compute snapshots lists` it gave me the permisions error. I've then check sudo permissions using `sudo gcloud auth list` and the service account was missing. So I've added the same service account with sudo and it worked. Didn't realise the service account didn't apply globally.

Thank you for your help.

**Comment by jacksegal** [comment]
No problem, glad you've got it working!
