### ISSUE TITLE
Device name length limitation

### ISSUE THREAD

**Issue by wdeviers** [jacksegal/google-compute-snapshot#48]
We name our disks pretty long, eg:

gcp-usc1-prod-ashdbuseractivity01-replica
gcp-usc1-prod-ashdbuseractivity01-replica-data

Which, when run through createSnapshotName(), generate name collisions during the snapshot.  Would you be opposed to a PR that strips out the device ID from createSnapShotName as an optional argument to the script?  Device name is more meaningful for us.

**Comment by wdeviers** [comment]
Works for me!  I'll see about hacking it in.

**Comment by jacksegal** [comment]
Hey @wdeviers - sorry I never got round to merging your PR - I merged another PR first and then never got round to sorting out the conflict.

Anyway, I've rewritten a large amount the script and it no longer uses Instance ID when naming snapshots!

(Resolved in #66)

**Comment by wdeviers** [comment]
Thanks! Appreciate you looking at it. I'll repull and change around my scripts.
