### ISSUE TITLE
Snapshot name bug

### ISSUE THREAD

**Issue by madsonic** [jacksegal/google-compute-snapshot#59]
[this line](https://github.com/jacksegal/google-compute-snapshot/blob/master/gcloud-snapshot.sh#L179) seems to be problematic. If the `${#req_chars}` is greater than `$name_max_len` the value would be negative which would cause `$device_name` to be substring differently

[As a reference](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) for the behaviour of substring expansion
> If offset evaluates to a number less than zero, the value is used as an offset in characters from the end of the value of parameter

_[14/11/2018: Issue was updated to reflect new line number]_

**Comment by jacksegal** [comment]
Good spot - this wasn't an issue originally as `${#req_chars}` was always less than `$name_max_len`, but now that users can set their own `$PREFIX` I guess it could happen.

What do you think about checking the length of `${#req_chars}` and if it's too long, substring the $PREFIX?
