### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by satrox28** [jacksegal/google-compute-snapshot#63]
Hi,

I am trying to execute the script but its keep throwing below error. I have created a Label for the disk autosnapshot:true(key:value). I would like to backup all the disks in a Zone which has the label.

 gcloud-snapshot.sh -t autosnaphot -z us-central1-a -a test@abc.iam.gserviceaccount.com

2018-11-07 13:53:39: Start of Script
2018-11-07 13:53:39: Start of createSnapshotWrapper
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
Usage: gcloud compute disks snapshot DISK_NAME [DISK_NAME ...] [optional flags]
  optional flags may be  --async | --csek-key-file | --description |
                         --guest-flush | --help | --snapshot-names | --zone

For detailed information on this command and its flags, run:
  gcloud compute disks snapshot --help
2018-11-07 13:53:40: Start of deleteSnapshotsWrapper
Listed 0 items.
2018-11-07 13:53:41: End of Script

Do am I missing any?.

$ gcloud --version
Google Cloud SDK 224.0.0
alpha 2018.11.02
app-engine-java 1.9.63
app-engine-python 1.9.67
beta 2018.11.02
bq 2.0.36
core 2018.11.02
gsutil 4.34
kubectl 2018.11.02

**Comment by jacksegal** [comment]
I've created a `debug` branch that has some logging to help me see which part of the script is failing for you.

Installation instructions for `debug` branch:

```
cd ~
wget https://raw.githubusercontent.com/jacksegal/google-compute-snapshot/debug/gcloud-snapshot.sh
chmod +x gcloud-snapshot.sh
sudo mkdir -p /opt/google-compute-snapshot
sudo mv gcloud-snapshot.sh /opt/google-compute-snapshot/
```
Then run the script with your options:
```
sudo /opt/google-compute-snapshot/gcloud-snapshot.sh -t autosnaphot -z us-central1-a -a test@abc.iam.gserviceaccount.com
```

If you include your output I can try and see which part isn't working.

Thanks,
Jack

**Comment by satrox28** [comment]
Thanks for your reply. As informed, have tried to execute and still see the same error.

Attached output as mentioned.

$ ./gcloud-snapshot.sh -t autosnaphot -z us-central1-a  -a snapshotadmin@lfco-prod-191202.iam.gserviceaccount.com
2018-11-08 01:32:51: Start of Script
2018-11-08 01:32:51: Start of createSnapshotWrapper
INSTANCE_NAME: test
INSTANCE_ZONE: us-central1-a
INSTANCE_ID: 8902563748388
DEVICE_LIST:
DEVICE_NAME:
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
Usage: gcloud compute disks snapshot DISK_NAME [DISK_NAME ...] [optional flags]
  optional flags may be  --async | --csek-key-file | --description |
                         --guest-flush | --help | --snapshot-names | --zone

For detailed information on this command and its flags, run:
  gcloud compute disks snapshot --help
2018-11-08 01:32:52: Start of deleteSnapshotsWrapper
Listed 0 items.
2018-11-08 01:32:53: End of Script

**Comment by satrox28** [comment]
Thanks for your reply. As informed, have tried to execute and still see the same error.

Attached output as mentioned.

$ ./gcloud-snapshot.sh -t autosnaphot -z us-central1-a -a test@abc.iam.gserviceaccount.com
2018-11-08 01:32:51: Start of Script
2018-11-08 01:32:51: Start of createSnapshotWrapper
INSTANCE_NAME: test
INSTANCE_ZONE: us-central1-a
INSTANCE_ID: 8902563748388
DEVICE_LIST:
DEVICE_NAME:
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
Usage: gcloud compute disks snapshot DISK_NAME [DISK_NAME ...] [optional flags]
optional flags may be --async | --csek-key-file | --description |
--guest-flush | --help | --snapshot-names | --zone

For detailed information on this command and its flags, run:
gcloud compute disks snapshot --help
2018-11-08 01:32:52: Start of deleteSnapshotsWrapper
Listed 0 items.
2018-11-08 01:32:53: End of Script

I am executing the script in remote system to backup selected volumes in our project.

**Comment by satrox28** [comment]
Hi,

Yes the Label and zone is correct. I am running this scripts from different zone, will it have any issue.

./gcloud-snapshot.sh -t autosnaphot -a test@abc.iam.gserviceaccount.com
2018-11-08 12:58:06: Start of Script
2018-11-08 12:58:06: Start of createSnapshotWrapper
INSTANCE_NAME: test
INSTANCE_ZONE: asia-southeast1-a
INSTANCE_ID: 123456
DEVICE_LIST:
DEVICE_NAME:
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
Usage: gcloud compute disks snapshot DISK_NAME [DISK_NAME ...] [optional flags]
  optional flags may be  --async | --csek-key-file | --description |
                         --guest-flush | --help | --snapshot-names | --zone

For detailed information on this command and its flags, run:
  gcloud compute disks snapshot --help
2018-11-08 12:58:07: Start of deleteSnapshotsWrapper
Listed 0 items.
2018-11-08 12:58:08: End of Script


$ ./gcloud-snapshot.sh -z us-central1-a -a test@abc.iam.gserviceaccount.com
2018-11-08 12:53:44: Start of Script
2018-11-08 12:53:44: Start of createSnapshotWrapper
INSTANCE_NAME: test
INSTANCE_ZONE: us-central1-a
INSTANCE_ID: 123456
DEVICE_LIST:
DEVICE_NAME:
ERROR: (gcloud.compute.disks.snapshot) argument --zone: expected one argument
Usage: gcloud compute disks snapshot DISK_NAME [DISK_NAME ...] [optional flags]
  optional flags may be  --async | --csek-key-file | --description |
                         --guest-flush | --help | --snapshot-names | --zone

For detailed information on this command and its flags, run:
  gcloud compute disks snapshot --help
2018-11-08 12:53:45: Start of deleteSnapshotsWrapper
Listed 0 items.
2018-11-08 12:53:46: End of Script

When I directly use gcloud command with filters retrieves the disk.
$ gcloud  compute disks list --filter "labels:autosnapshot" --format='value(name)'
vol-i-123445--dev-xvda-abcdefg

**Comment by jacksegal** [comment]
Hmmm, can you run this command:
```
$ gcloud compute disks list --filter "labels:autosnapshot"
```

It's the same command you ran to get the disk(s), but without the formatting - it will return all of the information about the disk(s)

**Comment by satrox28** [comment]
$  gcloud compute disks list --filter "labels:autosnapshot"
NAME                                        ZONE           SIZE_GB  TYPE    STATUS
vol-i-123445--dev-xvda-abcdefg  us-central1-a  10       pd-ssd  READY

**Comment by jacksegal** [comment]
I think there might be a typo in your first command - it says autosnaphot (missing an "s" before the "h" - autosnapshot).

Could that be the problem?  Does it work when you run this command (your original command, with the typo fixed):

```
$ ./gcloud-snapshot.sh -t autosnapshot -z us-central1-a -a test@abc.iam.gserviceaccount.com
```

**Comment by satrox28** [comment]
No I ran it without typo

**Comment by jacksegal** [comment]
Right, if you are running it on a "remote instance" then you need to also use the `[-i <instance_name]` input.  Where the `instance_name` is the name of the instance you want backed up.

**Comment by satrox28** [comment]
Noted, the script will not work only with the labels?.

**Comment by jacksegal** [comment]
Sorry, I'm not entirely sure what you mean?  

The script was primarily designed to only backup the instance that runs the script.  

It was extended to work with remote instances too, but to allow it to work with remote instances, you need to pass through the inputs `instance_name` and `instance_zone`.

Let me know if the script works when you pass in `instance_name`

**Comment by satrox28** [comment]
Hi, yes its working with instance name. In my previous reply I just asked whether is it possible to create snapshots from remote system without specifying instance name and just only provide label filters.

**Comment by jacksegal** [comment]
Great, glad to hear it's working!

No, that isn't currently possible - but is a probably a good idea for a future enhancement

**Comment by jacksegal** [comment]
@satrox28 ,

I ended up doing some changes to the script (#66) and it's now possible to backup remote instances without specifying instance info:

```
./gcloud-snapshot.sh -r
```

**Please note:** I've also removed the `-t` flag.  You can filter using the `-f` flag which uses [gcloud filter expressions](https://cloud.google.com/sdk/gcloud/reference/topic/filters) - for example to backup all remote disks with label of auto_snapshot=true:

```
./gcloud-compute-snapshot.sh -r -f "labels.auto_snapshot=true"
```

**Comment by satrox28** [comment]
@jacksegal 

It's working now, thanks. I am trying to execute the script with -d 5 but 6days snapshots are kept.

Below are the snapshots with Timestamp

gcs-vol-abc--dev-xvdc-abcde-1542326400
gcs-vol-abc--dev-xvdc-abcde-1542326400	
gcs-vol-abc--dev-xvdc-abcde-1542412800	
gcs-vol-abc--dev-xvdc-abcde-1542499200	
gcs-vol-abc--dev-xvdc-abcde-1542585600	
gcs-vol-abc--dev-xvdc-abcde-1542672000	
gcs-vol-abc--dev-xvdc-abcde-1542758400

**Comment by jacksegal** [comment]
Can you use "dry-run" mode (`-n`) and add the output to this issue?
