### ISSUE TITLE
[cronjob] executing cronjob issue

### ISSUE THREAD

**Issue by raramuridesign** [jacksegal/google-compute-snapshot#76]
Hi Jack
Thanks for the script, we do not have any issues running the script manually from the command line using this:

sudo /opt/google-compute-snapshot/gcloud-snapshot.sh

However, when we try to set the cronjob, it just will not execute
We are using Ubuntu 18.

To test we have set the cron to run every 10 min, but we do not see any results.
We are using
0 5 * * * root /opt/google-compute-snapshot/gcloud-snapshot.sh > /dev/null 2>&1

Editing the crontab located here
nano /etc/crontab

Also tried editing crontab -e but this has no effect.

Would you by any chance have an idea if we are doing something wrong?

Thanks
Matthew

**Comment by jacksegal** [comment]
Hi Matthew,

Have you reloaded your cron service? (`$  sudo service cron reload`)

Also, the example you provided runs at 5am - does your test one (that runs every 10 mins) look like this: 
```
*/10 * * * * root /opt/google-compute-snapshot/gcloud-snapshot.sh > /dev/null 2>&1
```

You can also check for crontab errors here: `/var/log/syslog`

Thanks,
Jack

**Comment by jacksegal** [comment]
Hmmmm - okay, I'd try saving the output of the log to a file: [https://github.com/jacksegal/google-compute-snapshot#saving-output-to-log](https://github.com/jacksegal/google-compute-snapshot#saving-output-to-log)

It only takes about 5 minutes to setup and then you'll be able to see the output from the script.

Good luck!

**Comment by raramuridesign** [comment]
@jacksegal 
so I have added the log which outputs this info

`
Listed 0 items.
[2018-11-22 16:15:45]: End of google-compute-snapshot
[2018-11-22 16:20:01]: Start of google-compute-snapshot
/opt/google-compute-snapshot/gcloud-snapshot.sh: line 157: gcloud: command not found
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
[ERROR]: No disks were found - please check your script options / account permissions.
`

I had a look through the code and do not understand why the instance is not being picked up.
Any ideas.
Matthew

**Comment by jacksegal** [comment]
The first error: `gcloud: command not found` suggests that CRON can't access `gcloud`.  Did you install `gcloud` manually on the server?

I had a quick google and found these on Stackoverflow: 

- [https://stackoverflow.com/a/53416714/5953656](https://stackoverflow.com/a/53416714/5953656)
- [https://stackoverflow.com/q/31037279/5953656](https://stackoverflow.com/q/31037279/5953656)

Hope it helps!

**Comment by raramuridesign** [comment]
Thanks @jacksegal
