### ISSUE TITLE
WARNING Argument `NAME` is deprecated

### ISSUE THREAD

**Issue by rajeshgeeks** [jacksegal/google-compute-snapshot#78]
[2018-11-23 06:03:13]: Start of google-compute-snapshot
WARNING: Argument `NAME` is deprecated. Use `--filter="name=( 'NAME' ... )"` instead.
How to include the DATE stamp in dd-mm-yyyy format?

Please, look into this. 

//Rajesh

**Comment by jacksegal** [comment]
I've fixed depreciation WARNING in latest release.

If you want to change the date format, you need to edit this line: https://github.com/jacksegal/google-compute-snapshot/blob/master/gcloud-snapshot.sh#L344

Change: 
```
DATE_TIME="$(date "+%s")"
```

To:
```
DATE_TIME="$(date "+%d-%m-%Y")"
```
