### ISSUE TITLE
Syntax error on line 266: "(" unexpected (expecting "}")

### ISSUE THREAD

**Issue by alemens** [jacksegal/google-compute-snapshot#81]
Error: 
`gcloud-snapshot.sh: 266: gcloud-snapshot.sh: Syntax error: "(" unexpected (expecting "}")
`

**Comment by alemens** [comment]
uname -a
`Linux cron 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

**Comment by jacksegal** [comment]
Hi @alemens 

I think this might be of use to you: [https://stackoverflow.com/a/18921455/5953656](https://stackoverflow.com/a/18921455/5953656)

Try running it with bash
