### ISSUE TITLE
-r option - How to Backup remote instances "only"?

### ISSUE THREAD

**Issue by alemens** [jacksegal/google-compute-snapshot#82]
About the `-r` option described here [https://github.com/jacksegal/google-compute-snapshot#backing-up-remote-instances](url) 
The function it works for: "Backup remote instances too" **what if** I would like to "Backup remote instances only"?

**Comment by alemens** [comment]
I think this feature it is a nice to have only. And you @jacksegal already did a great job. Thank you for the solution

**Comment by jacksegal** [comment]
Thanks @alemens!  

You could do this using the filter option (-f), excluding the instance you are calling from.  For example, replacing ${instance_name} with the name of your calling instance:

```./gcloud-snapshot.sh -f "users~instances/${instance_name}\$"```

e.g. if your calling instance was called `instance-1`:

```./gcloud-snapshot.sh -f "users~instances/instance-1\$"```
