### ISSUE TITLE
Service account usage

### ISSUE THREAD

**Issue by briffle** [jacksegal/google-compute-snapshot#85]
I see the -a flag for service accounts, and you pass the value in, but how do you first activate it? (or do you need to?)  if I'm going to run this via cron, do I first need to run:

> /usr/bin/gcloud auth activate-service-account --key-file "${SERVICE_ACCT_KEY_FILE}" --project ${PROJECT_NAME}

Or will it otherwise figure that out?  That isn't described in the readme, and may be confusing to some.

The script would be easier to deploy via a template in tools like Ansible/saltstack/etc, if I could pass in the json file as an option, instead of the account email id string.  That would limit the number of commands that need to be run, input parsed, etc, on each remote computer.

**Comment by jacksegal** [comment]
Sorry @briffle - I don't know the answer to this question!

The `-a` flag for service accounts was added by a contributor - I've never used them whilst running the script.

From a quick look at the docs, I think you are right that you need to run the `gcloud auth activate-service-account` command first.

I agree that adding an option for the `SERVICE_ACCT_KEY_FILE`, and then running the `gcloud auth activate-service-account` command if it exists is a good idea.  However I don't have the time to do this at the moment, particularly as I don't even use Service Accounts when I run the script.  

If you'd like to do a PR for this change, then I'm happy to merge it in.  Thanks for the feedback.
