### ISSUE TITLE
No disk were found

### ISSUE THREAD

**Issue by hugokx** [jacksegal/google-compute-snapshot#88]
Hi, 

I am running the last instance of your script and I get the error 

[ERROR]: No disks were found - please check your script options / account permissions.

here is the output of gcloud compute disks list

gcloud compute disks list
NAME                                 ZONE            SIZE_GB  TYPE    STATUS
vol-8796758176650--dev-sda-a92b0d8e  europe-west1-b  51       pd-ssd  READY

How can I resolve this issue ?

Thanks,

Hugues.

**Comment by jacksegal** [comment]
Hi @hugokx 

What command are you using to run the script? `sudo /opt/google-compute-snapshot/gcloud-snapshot.sh` ? 

Can you try running the script with the `-n` flag (Dry run)?  It runs the script in debug and provides some helpful output.

Thanks,
Jack

**Comment by jcroucher** [comment]
I am having the same issue

[root@*** ***]# ./gcloud-snapshot.sh -n
[2019-01-16 02:52:40]: Start of google-compute-snapshot
[DEBUG]: OLDER_THAN=7
[DEBUG]: REMOTE_CLAUSE=
[DEBUG]: FILTER_CLAUSE=
[DEBUG]: PREFIX=gcs
[DEBUG]: OPT_ACCOUNT=
[DEBUG]: OPT_PROJECT=
[DEBUG]: DRY_RUN=true
[DEBUG]: DATE_TIME=1547607160
[DEBUG]: DELETION_DATE=20190109
[DEBUG]: INSTANCE_NAME=***
ERROR: (gcloud.compute.disks.list) Some requests did not succeed:
 - Insufficient Permission

[ERROR]: No disks were found - please check your script options / account permissions.

**Comment by jacksegal** [comment]
Thanks @jcroucher - glad you resolved it.  There is a bit in Prerequisites section of README which touches on API permissions - I've also got issue #73 open to check the permissions are error gracefully.

I think @hugokx issue is different, because they are able to successfully get the list of disks when running the `gcloud compute disks list` command outside of the script.

**Comment by hugokx** [comment]
Hi @jacksegal 

Here is what I got when I run without parameters and with a dry run

`runew@runew-virtualbox-73237c60:~$ sudo /opt/google-compute-snapshot/gcloud-snap                                  shot.sh`
`[sudo] password for runew:`
`
[2019-01-16 23:35:04]: Start of google-compute-snapshot
/opt/google-compute-snapshot/gcloud-snapshot.sh: line 190: gcloud: command not f                                  ound
`
`[ERROR]: No disks were found - please check your script options / account permis                                  sions.`
`runew@runew-virtualbox-73237c60:~$ sudo /opt/google-compute-snapshot/gcloud-snap                                  shot.sh -n`
`[2019-01-16 23:35:10]: Start of google-compute-snapshot`
`[DEBUG]: OLDER_THAN=7`
`[DEBUG]: REMOTE_CLAUSE=`
`[DEBUG]: FILTER_CLAUSE=`
`[DEBUG]: PREFIX=gcs`
`[DEBUG]: OPT_ACCOUNT=`
`[DEBUG]: OPT_PROJECT=`
`[DEBUG]: DRY_RUN=true`
`[DEBUG]: DATE_TIME=1547667310`
`[DEBUG]: DELETION_DATE=20190109`
`[DEBUG]: INSTANCE_NAME=runew-virtualbox-73237c60`
`/opt/google-compute-snapshot/gcloud-snapshot.sh: line 190: gcloud: command not f                                  ound`
`[ERROR]: No disks were found - please check your script options / account permis                                  sions.`

Thanks à lot

**Comment by jacksegal** [comment]
@hugokx - can try running the command without `sudo`?

```
/opt/google-compute-snapshot/gcloud-snapshot.sh -n
```

I think that should solve your problem.

**Comment by bishopjon** [comment]
Not sure if this helps anyone... If you run it manually as root it works but running it with cron as root it does not work. For some reason even if the cron runs it as root you still need the sudo.

See the screenshot... If I take out sudo it does not work and gives the no disks were found error.

<img width="492" alt="screen shot 2019-01-19 at 4 32 22 pm" src="https://user-images.githubusercontent.com/5399938/51432572-d7a87100-1c07-11e9-92b1-9ea69317853f.png">

**Comment by hugokx** [comment]
> @hugokx - can try running the command without `sudo`?
> 
> ```
> /opt/google-compute-snapshot/gcloud-snapshot.sh -n
> ```
> I think that should solve your problem.

runew@runew-virtualbox-73237c60:~$ /opt/google-compute-snapshot/gcloud-snapshot.                                sh -n
[2019-01-20 21:56:01]: Start of google-compute-snapshot
[DEBUG]: OLDER_THAN=7
[DEBUG]: REMOTE_CLAUSE=
[DEBUG]: FILTER_CLAUSE=
[DEBUG]: PREFIX=gcs
[DEBUG]: OPT_ACCOUNT=
[DEBUG]: OPT_PROJECT=
[DEBUG]: DRY_RUN=true
[DEBUG]: DATE_TIME=1548006961
[DEBUG]: DELETION_DATE=20190113
[DEBUG]: INSTANCE_NAME=runew-virtualbox-73237c60
[DEBUG]: DEVICE_LIST=vol-8796758176650--dev-sda-a92b0d8e        europe-west1-b 6                                065151830339443868
[2019-01-20 21:56:03]: Handling Snapshots for vol-8796758176650--dev-sda-a92b0d8                                e
[CMD]: gcloud  compute snapshots delete gcs-vol-8796758176650--dev-sda-a92b0d8e-                                1546357783 -q
[CMD]: gcloud  compute disks snapshot vol-8796758176650--dev-sda-a92b0d8e --snap                                shot-names gcs-vol-8796758176650--dev-sda-a92b0d8e-1548006961 --zone europe-west 

but my crontab is not sudo

@daily /opt/google-compute-snapshot/gcloud-snapshot.sh -d 7 >> /var/log/cron/snapshot.log 2>&1

**Comment by hugokx** [comment]
Hi, 

Thank for your help

crontab is not run with root. I only use

crontab -e (no sudo) then use the command in the previous answer.

Here is what I get in the log file

  GNU nano 2.5.3                           File: snapshot.log.1

[2019-01-21 00:00:01]: Start of google-compute-snapshot
/opt/google-compute-snapshot/gcloud-snapshot.sh: line 190: gcloud: command not found
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
[ERROR]: No disks were found - please check your script options / account permissions.

**Comment by jacksegal** [comment]
No problem!  Can you run the following command and let me know the output?
```
which gcloud
```
Also, can you paste your crontab into here too?  I'm looking for any instances of `PATH=`

**Comment by hugokx** [comment]
Hi,

Here is the output of which gcloud

/home/runew/google-cloud-sdk/bin/gcloud

so gcloud is not running on root.

and there is no instance of PATH in crontab. The only line is the commande for your script that I pasted here before.

Thank you ! :-)

**Comment by ghost** [comment]
is anyone fix this issue?

No disks were found - please check your script options / account permissions

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/96846770/174394783-c9a919ef-8133-433e-8b2f-913a430ba1ac.png)

**Comment by jacksegal** [comment]
Hi @ronaldoramosgit-ti  - 

Have you checked whether the VM has the sufficient gcloud permissions? 

Including "compute" set to "enabled": http://stackoverflow.com/questions/31905966/gcloud-compute-list-networks-error-some-requests-did-not-succeed-insufficie#31928399
