### ISSUE TITLE
gcloud auth?

### ISSUE THREAD

**Issue by leeblackwell** [jacksegal/google-compute-snapshot#90]
Good morning... 

On a GCP VM, running the script from command line works as expected:

```
root@hal:/opt/google-compute-snapshot# /opt/google-compute-snapshot/gcloud-snapshot.sh -p hal
[2019-01-28 10:54:36]: Start of google-compute-snapshot
[2019-01-28 10:54:37]: Handling Snapshots for hal
Listed 0 items.
Creating snapshot(s) hal-hal-1548672876...
..............done.
[2019-01-28 10:54:52]: Handling Snapshots for rsyslog-disk
Listed 0 items.
Creating snapshot(s) hal-rsyslog-disk-1548672876...
................................done.
[2019-01-28 10:55:22]: End of google-compute-snapshot
```

But from a cron job:
```
51 10 * * * /opt/google-compute-snapshot/gcloud-snapshot.sh -p hal > /opt/google-compute-snapshot/gcloud-snapshot.log
```

... there's 'no disks':
```
root@hal:/opt/google-compute-snapshot# cat /opt/google-compute-snapshot/gcloud-snapshot.log
[2019-01-28 10:51:01]: Start of google-compute-snapshot
[ERROR]: No disks were found - please check your script options / account permissions.
```

I suspected gcloud auth, but that looks correct:
```
root@hal:/opt/google-compute-snapshot# gcloud auth list
                  Credentialed Accounts
ACTIVE  ACCOUNT
*       3__________9-compute@developer.gserviceaccount.com

To set the active account, run:
    $ gcloud config set account `ACCOUNT`

root@hal:/opt/google-compute-snapshot# 
```

Checked path too:
```
root@hal:/opt/google-compute-snapshot# which gcloud
/snap/bin/gcloud
root@hal:/opt/google-compute-snapshot# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
root@hal:/opt/google-compute-snapshot# 
```

After some testing, it appears that gcloud auth was indeed the issue; when executed from cron, it appears that root's environment isn't picked up, and as such, there's no auth.

A workaround was to change cron line to make use of sudo:
```
0 1 * * * sudo -u root /opt/google-compute-snapshot/gcloud-snapshot.sh -q -p hal 2>&1 > /opt/google-compute-snapshot/gcloud-snapshot.log
```

I appreciate that this isn't an issue with your script, but figured the workaround may be useful to others if added to documentation.

Best,
-Lee

**Comment by jacksegal** [comment]
Thanks for your feedback @leeblackwell - I'll update the README to include the `sudo`

**Comment by jacksegal** [comment]
Finally got round to it!  Thanks again

**Comment by timwsuqld** [comment]
@jacksegal I'm not sure the update to the README is correct. @leeblackwell appears to be running the crontab entry from a users crontab. Your readme correctly had "root" at the start of the crontab file, which in /etc/crontab says to run as root. Maybe the update to the readme should be to explain where to put the crontab.

If putting in a users crontab, then you'll want to put it in the ```root``` users crontab, and then the correct line is 
```
0 5 * * * /opt/google-compute-snapshot/gcloud-snapshot.sh > /dev/null 2>&1 
```
Which is what @leeblackwell appeared to have.

If putting it in a system crontab (/etc/crontab) then what you had in the readme before is correct.
```
0 5 * * * root /opt/google-compute-snapshot/gcloud-snapshot.sh > /dev/null 2>&1
```

Sudo shouldn't be used in a crontab, as often sudo requires a password to work, which won't work in a crontab. You should instead put the cron entry in the correct users crontab to start with, so sudo isn't required.

**Comment by jacksegal** [comment]
Hi @leeblackwell 

Can you confirm how you are running the cron?

Is it from the system crontab (/etc/crontab)?  Or from a user's crontab (crontab -e)?
