### ISSUE TITLE
-g options seems not handled

### ISSUE THREAD

**Issue by shwuhk** [jacksegal/google-compute-snapshot#99]
-g option set the opt_g to true but it did not handled in the command. Thanks.

**Comment by jacksegal** [comment]
Hi @shwuhk 

Can you add the `-n` option and provide the output?  (you'll need to include the other options as well)

It runs the command in debug mode and provides some useful info.

Thanks,
Jack

**Comment by shwuhk** [comment]
root@backup:~# ./gcloud-snapshot.sh -d 14 -r -g -n
[2019-06-26 03:12:07]: Start of google-compute-snapshot
[DEBUG]: OLDER_THAN=14
[DEBUG]: REMOTE_CLAUSE=true
[DEBUG]: FILTER_CLAUSE=
[DEBUG]: PREFIX=gcs
[DEBUG]: OPT_ACCOUNT=
[DEBUG]: OPT_PROJECT=
[DEBUG]: DRY_RUN=true
[DEBUG]: COPY_LABELS=
[DEBUG]: OPT_SNAPSHOT_LOCATION=
[DEBUG]: DATE_TIME=1561518727
[DEBUG]: DELETION_DATE=20190612
[DEBUG]: INSTANCE_NAME=
[DEBUG]: DEVICE_LIST=application        https://www.googleapis.com/compute/v1/projects/xxxxxxx/zones/asia-east1-b  xxxxxxx
[2019-06-26 03:12:13]: Handling Snapshots for application
Listed 0 items.
[CMD]: gcloud  compute disks snapshot application --snapshot-names gcs-application-1561518727 --zone https://www.googleapis.com/compute/v1/projects/xxxxxxx/zones/asia-east1-b
[2019-06-26 03:12:13]: Handling Snapshots for backup


Thanks

**Comment by shwuhk** [comment]
I found the bug and submit a pull request. Please accept. Thanks.

https://github.com/jacksegal/google-compute-snapshot/pull/100

**Comment by jacksegal** [comment]
thanks for PR!
